In [3]:
!pip install transformers

In [4]:
from transformers import pipeline

In [5]:
classifier = pipeline("sentiment-analysis") # by default loading the distilbert model

No model was supplied, defaulted to distilbert/distilbert-base-uncased-finetuned-sst-2-english and revision 714eb0f (https://huggingface.co/distilbert/distilbert-base-uncased-finetuned-sst-2-english).
Using a pipeline without specifying a model name and revision in production is not recommended.


config.json:   0%|          | 0.00/629 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/268M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

Device set to use cpu


### Imp.Points :
- By default, this pipeline uses distilbert-base-uncased-finetuned-sst-2-english

- Here, uncased means it can handle case sensitivity.

- It have same actions for "apple" and "Apple"

- sst-2 stands for Standford Sentiment Treebank-2 -> Dataset from Hugging Face

- HF_TOKEN is used to use the model which sst-2, it allows us to use that model

In [6]:
classifier("I will learn AI throughout my entire life, it is like a passion")

[{'label': 'POSITIVE', 'score': 0.9987820982933044}]

In [7]:
classifier("I am not able to complete that project on time, if you behave like this.")

[{'label': 'NEGATIVE', 'score': 0.9997578263282776}]

In [8]:
# HF_TOKEN = "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", OLD = "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"

In [9]:
generation = pipeline("text-generation")

No model was supplied, defaulted to openai-community/gpt2 and revision 607a30d (https://huggingface.co/openai-community/gpt2).
Using a pipeline without specifying a model name and revision in production is not recommended.


config.json:   0%|          | 0.00/665 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/548M [00:00<?, ?B/s]

generation_config.json:   0%|          | 0.00/124 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/26.0 [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/1.04M [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/456k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.36M [00:00<?, ?B/s]

Device set to use cpu


In [10]:
generation("what is the latest version of Tensorflow")

Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.


[{'generated_text': 'what is the latest version of Tensorflow? What about the latest version of the TensorFlow API? How does this help you?'}]

In [11]:
generation("What is Pytorch")

Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.


[{'generated_text': 'What is Pytorch: PyTorch? Why not just tell me? And for what it\'s worth, all my other reviews were "just to make sure I had as much fun as possible", you\'re welcome...\n\n\nWhat does it'}]

In [12]:
summarization = pipeline("summarization")

No model was supplied, defaulted to sshleifer/distilbart-cnn-12-6 and revision a4f8f3e (https://huggingface.co/sshleifer/distilbart-cnn-12-6).
Using a pipeline without specifying a model name and revision in production is not recommended.


config.json:   0%|          | 0.00/1.80k [00:00<?, ?B/s]

pytorch_model.bin:   0%|          | 0.00/1.22G [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/1.22G [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/26.0 [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/899k [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/456k [00:00<?, ?B/s]

Device set to use cpu


In [13]:
summarization("Hugging Face, Inc. is an American company incorporated under the Delaware General Corporation Law[1] and based in New York City that develops computation tools for building applications using machine learning. It is most notable for its transformers library built for natural language processing applications and its platform that allows users to share machine learning models and datasets and showcase their work.")

Your max_length is set to 142, but your input_length is only 72. Since this is a summarization task, where outputs shorter than the input are typically wanted, you might consider decreasing max_length manually, e.g. summarizer('...', max_length=36)


[{'summary_text': ' Hugging Face, Inc. is an American company that develops computation tools for building applications using machine learning . It is most notable for its transformers library built for natural language processing applications and its platform that allows users to share machine learning models and datasets and showcase their work .'}]

In [14]:
summarization("A large language model (LLM) is a machine learning model that can understand and generate human-like text. LLMs are trained on massive amounts of data and are used for natural language processing (NLP) tasks. ")

Your max_length is set to 142, but your input_length is only 48. Since this is a summarization task, where outputs shorter than the input are typically wanted, you might consider decreasing max_length manually, e.g. summarizer('...', max_length=24)


[{'summary_text': ' A large language model (LLM) is a machine learning model that can understand and generate human-like text . LLMs are trained on massive amounts of data and are used for natural language processing (NLP) tasks . They are used in natural language tasks such as NLP tasks .'}]

In [15]:
text = "A large language model (LLM) is a machine learning model that can understand and generate human-like text. LLMs are trained on massive amounts of data and are used for natural language processing (NLP) tasks. "

In [16]:
summarization(text,max_length=10)

Your min_length=56 must be inferior than your max_length=10.
/usr/local/lib/python3.11/dist-packages/transformers/generation/utils.py:1427: UserWarning: Unfeasible length constraints: `min_length` (56) is larger than the maximum possible length (10). Generation will stop at the defined maximum length. You should decrease the minimum length and/or increase the maximum length.
  warnings.warn(


[{'summary_text': ' A large language model (LLM'}]

### There are 3 ways to load any model like text-generation,summarization or sentiment-analysis,etc.
1. Through API(like OPENAI API, Groq API)
2. In memory(directly)
3. In disk

> **Here, in the above code, we are loading the model directly into memory.**


In [17]:
classifier = pipeline("zero-shot-classification")

No model was supplied, defaulted to facebook/bart-large-mnli and revision d7645e1 (https://huggingface.co/facebook/bart-large-mnli).
Using a pipeline without specifying a model name and revision in production is not recommended.


config.json:   0%|          | 0.00/1.15k [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/1.63G [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/26.0 [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/899k [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/456k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.36M [00:00<?, ?B/s]

Device set to use cpu


In [18]:
res = classifier(
    "This is a course about Python list comprehension",
    candidate_labels=["education", "politics", "business"]
)

In [19]:
print(res)

{'sequence': 'This is a course about Python list comprehension', 'labels': ['education', 'business', 'politics'], 'scores': [0.9622026681900024, 0.026841413229703903, 0.010955973528325558]}


## Observation :
1. zero-shot classification gives the score to the list of labels for a particular sentence.

# Custom model creation in Pipeline

In [20]:
bert_summarizer = pipeline("summarization",model="google-bert/bert-base-uncased")

config.json:   0%|          | 0.00/570 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/440M [00:00<?, ?B/s]

BertForMaskedLM has generative capabilities, as `prepare_inputs_for_generation` is explicitly overwritten. However, it doesn't directly inherit from `GenerationMixin`. From 👉v4.50👈 onwards, `PreTrainedModel` will NOT inherit from `GenerationMixin`, and this model will lose the ability to call `generate` and other related functions.
  - If you're using `trust_remote_code=True`, you can get rid of this warning by loading the model with an auto class. See https://huggingface.co/docs/transformers/en/model_doc/auto#auto-classes
  - If you are the owner of the model architecture code, please modify your model class such that it inherits from `GenerationMixin` (after `PreTrainedModel`, otherwise you'll get an exception).
  - If you are not the owner of the model architecture class, please contact the model code owner to update it.
Some weights of the model checkpoint at google-bert/bert-base-uncased were not used when initializing BertForMaskedLM: ['bert.pooler.dense.bias', 'bert.pooler.dense

tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

Device set to use cpu
The model 'BertForMaskedLM' is not supported for summarization. Supported models are ['BartForConditionalGeneration', 'BigBirdPegasusForConditionalGeneration', 'BlenderbotForConditionalGeneration', 'BlenderbotSmallForConditionalGeneration', 'EncoderDecoderModel', 'FSMTForConditionalGeneration', 'GPTSanJapaneseForConditionalGeneration', 'LEDForConditionalGeneration', 'LongT5ForConditionalGeneration', 'M2M100ForConditionalGeneration', 'MarianMTModel', 'MBartForConditionalGeneration', 'MT5ForConditionalGeneration', 'MvpForConditionalGeneration', 'NllbMoeForConditionalGeneration', 'PegasusForConditionalGeneration', 'PegasusXForConditionalGeneration', 'PLBartForConditionalGeneration', 'ProphetNetForConditionalGeneration', 'Qwen2AudioForConditionalGeneration', 'SeamlessM4TForTextToText', 'SeamlessM4Tv2ForTextToText', 'SwitchTransformersForConditionalGeneration', 'T5ForConditionalGeneration', 'UMT5ForConditionalGeneration', 'XLMProphetNetForConditionalGeneration'].


In [21]:
text

'A large language model (LLM) is a machine learning model that can understand and generate human-like text. LLMs are trained on massive amounts of data and are used for natural language processing (NLP) tasks. '

In [22]:
print(bert_summarizer(text))

[{'summary_text': 'a large language model ( llm ) is a machine learning model that can understand and generate human - like text. llms are trained on massive amounts of data and are used for natural language processing ( nlp ) tasks. these include grammar. large languages and large languages are trained on. languages.. large. large natural'}]


In [23]:
print(bert_summarizer(text,max_new_tokens=10))

[{'summary_text': 'a large language model ( llm ) is a machine learning model that can understand and generate human - like text. llms are trained on massive amounts of data and are used for natural language processing ( nlp ) tasks. these include grammar. large languages and large languages are'}]


In [24]:
from transformers import AutoTokenizer
model_name = "nlptown/bert-base-multilingual-uncased-sentiment"
tokenizer = AutoTokenizer.from_pretrained(model_name)

tokenizer_config.json:   0%|          | 0.00/39.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/953 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/872k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

In [25]:
tf_batch = tokenizer(
    ["We are very happy to show you the 🤗 Transformers library.", "We hope you don't hate it."],
    padding=True,
    truncation=True,
    max_length=512,
    return_tensors="tf",
)

In [26]:
tf_batch

{'input_ids': <tf.Tensor: shape=(2, 14), dtype=int32, numpy=
array([[  101, 11312, 10320, 12495, 19308, 10114, 11391, 10855, 10103,
          100, 58263, 13299,   119,   102],
       [  101, 11312, 18763, 10855, 11530,   112,   162, 39487, 10197,
          119,   102,     0,     0,     0]], dtype=int32)>, 'token_type_ids': <tf.Tensor: shape=(2, 14), dtype=int32, numpy=
array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]], dtype=int32)>, 'attention_mask': <tf.Tensor: shape=(2, 14), dtype=int32, numpy=
array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0]], dtype=int32)>}

In [27]:
from transformers import AutoTokenizer, AutoModelForSequenceClassification

- sent --> tokens --> embedding --> positional_encoding --> self_attention --> feed_forwardNN --> o/p

> vocab size will be different for every type of model like BERT or GPT

## Tokenization techniques
- python --> split()
- spacy
- nltk

In [28]:
tokenizer = AutoTokenizer.from_pretrained("google/flan-t5-large")

tokenizer_config.json:   0%|          | 0.00/2.54k [00:00<?, ?B/s]

spiece.model:   0%|          | 0.00/792k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/2.42M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/2.20k [00:00<?, ?B/s]

In [30]:
model = AutoModelForSequenceClassification.from_pretrained("google/flan-t5-large")

config.json:   0%|          | 0.00/662 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/3.13G [00:00<?, ?B/s]

Some weights of T5ForSequenceClassification were not initialized from the model checkpoint at google/flan-t5-large and are newly initialized: ['classification_head.dense.bias', 'classification_head.dense.weight', 'classification_head.out_proj.bias', 'classification_head.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


In [31]:
tokenizer

T5TokenizerFast(name_or_path='google/flan-t5-large', vocab_size=32100, model_max_length=512, is_fast=True, padding_side='right', truncation_side='right', special_tokens={'eos_token': '</s>', 'unk_token': '<unk>', 'pad_token': '<pad>', 'additional_special_tokens': ['<extra_id_0>', '<extra_id_1>', '<extra_id_2>', '<extra_id_3>', '<extra_id_4>', '<extra_id_5>', '<extra_id_6>', '<extra_id_7>', '<extra_id_8>', '<extra_id_9>', '<extra_id_10>', '<extra_id_11>', '<extra_id_12>', '<extra_id_13>', '<extra_id_14>', '<extra_id_15>', '<extra_id_16>', '<extra_id_17>', '<extra_id_18>', '<extra_id_19>', '<extra_id_20>', '<extra_id_21>', '<extra_id_22>', '<extra_id_23>', '<extra_id_24>', '<extra_id_25>', '<extra_id_26>', '<extra_id_27>', '<extra_id_28>', '<extra_id_29>', '<extra_id_30>', '<extra_id_31>', '<extra_id_32>', '<extra_id_33>', '<extra_id_34>', '<extra_id_35>', '<extra_id_36>', '<extra_id_37>', '<extra_id_38>', '<extra_id_39>', '<extra_id_40>', '<extra_id_41>', '<extra_id_42>', '<extra_id_43>

In [32]:
model

T5ForSequenceClassification(
  (transformer): T5Model(
    (shared): Embedding(32128, 1024)
    (encoder): T5Stack(
      (embed_tokens): Embedding(32128, 1024)
      (block): ModuleList(
        (0): T5Block(
          (layer): ModuleList(
            (0): T5LayerSelfAttention(
              (SelfAttention): T5Attention(
                (q): Linear(in_features=1024, out_features=1024, bias=False)
                (k): Linear(in_features=1024, out_features=1024, bias=False)
                (v): Linear(in_features=1024, out_features=1024, bias=False)
                (o): Linear(in_features=1024, out_features=1024, bias=False)
                (relative_attention_bias): Embedding(32, 16)
              )
              (layer_norm): T5LayerNorm()
              (dropout): Dropout(p=0.1, inplace=False)
            )
            (1): T5LayerFF(
              (DenseReluDense): T5DenseGatedActDense(
                (wi_0): Linear(in_features=1024, out_features=2816, bias=False)
                (w

In [33]:
save_directory = "my_model_dir"

In [34]:
tokenizer.save_pretrained(save_directory)

('my_model_dir/tokenizer_config.json',
 'my_model_dir/special_tokens_map.json',
 'my_model_dir/spiece.model',
 'my_model_dir/added_tokens.json',
 'my_model_dir/tokenizer.json')

In [35]:
model.save_pretrained(save_directory)

- text --> audio
- text --> images