In [1]:
import torch

In [2]:
import torch.nn as nn

In [3]:
class Model(nn.Module):
    def __init__(self,new_features):
      super().__init__()
      self.linear = nn.Linear(new_features,1) # helps to create input and hidden layer corresponding to size of new_features
      self.sigmoid = nn.Sigmoid() # helps to create an output layer

    def forward(self,features):
      out = self.linear(features)
      out = self.sigmoid(out)
      return out

In [4]:
import torch
features = torch.rand(10,5)

In [5]:
features.shape

torch.Size([10, 5])

In [6]:
features.shape[0],features.shape[1]

(10, 5)

In [7]:
# Linear equation for forward propogation --> z = wx + b
model = Model(features.shape[1])

In [8]:
class test:
  def __init__(self):
    print("hello from init")
  def __call__(self):
    print("hello from call")
  def testing(self):
    print("hello from testing")

In [9]:
obj = test()

hello from init


In [10]:
obj.testing()

hello from testing


In [11]:
# Calling obj as function
obj()

hello from call


In [12]:
model(features)

tensor([[0.4775],
        [0.5029],
        [0.5652],
        [0.5588],
        [0.5383],
        [0.4931],
        [0.4998],
        [0.5425],
        [0.5231],
        [0.4722]], grad_fn=<SigmoidBackward0>)

In [13]:
model.forward(features) ## model.forward(features) == model(features)

tensor([[0.4775],
        [0.5029],
        [0.5652],
        [0.5588],
        [0.5383],
        [0.4931],
        [0.4998],
        [0.5425],
        [0.5231],
        [0.4722]], grad_fn=<SigmoidBackward0>)

In [14]:
model.linear.weight

Parameter containing:
tensor([[-0.1675,  0.0384,  0.0461,  0.1004, -0.3742]], requires_grad=True)

In [15]:
model.linear.bias

Parameter containing:
tensor([0.2911], requires_grad=True)

## weights and biases in linear model
- For 5 features, 5 weights are there and 1 bias --> Total of 6 parameters

In [16]:
class Model(nn.Module):
    def __init__(self,new_features):
      super().__init__()
      self.linear1 = nn.Linear(new_features,3) # helps to create input and hidden layer corresponding to size of new_features
      self.relu = nn.ReLU() # helps to create an activation function
      self.linear2 = nn.Linear(3,1)
      self.sigmoid = nn.Sigmoid() # helps to create an output layer

    def forward(self,features):
      out = self.linear1(features)
      out = self.relu(out)
      out = self.linear2(out)
      out = self.sigmoid(out)
      return out

In [17]:
data = torch.rand(10,5)

In [18]:
data

tensor([[0.5501, 0.3121, 0.7687, 0.2026, 0.8324],
        [0.7503, 0.6700, 0.9805, 0.2186, 0.7995],
        [0.9342, 0.5317, 0.9035, 0.7263, 0.3508],
        [0.1309, 0.1283, 0.1127, 0.3699, 0.6443],
        [0.3353, 0.2226, 0.1467, 0.8741, 0.5769],
        [0.4270, 0.8772, 0.6045, 0.9303, 0.8784],
        [0.8060, 0.1253, 0.2140, 0.6976, 0.7078],
        [0.8020, 0.8128, 0.3431, 0.3277, 0.0158],
        [0.9900, 0.8781, 0.2176, 0.2321, 0.8450],
        [0.7442, 0.5995, 0.0757, 0.4628, 0.4247]])

In [19]:
model = Model(data.shape[1]) # data.shape[1]

In [20]:
model.forward(data)

tensor([[0.6919],
        [0.6958],
        [0.6823],
        [0.6726],
        [0.6657],
        [0.6809],
        [0.6671],
        [0.6680],
        [0.6723],
        [0.6632]], grad_fn=<SigmoidBackward0>)

In [21]:
model(data) # for every there is 1 weight --> here, no. of rows = 10

tensor([[0.6919],
        [0.6958],
        [0.6823],
        [0.6726],
        [0.6657],
        [0.6809],
        [0.6671],
        [0.6680],
        [0.6723],
        [0.6632]], grad_fn=<SigmoidBackward0>)

In [22]:
model.linear1.weight # as linear1 have (5,3) --> 5x3 = 15

Parameter containing:
tensor([[ 0.2670, -0.2558,  0.1650,  0.1443, -0.0011],
        [-0.0791,  0.0007,  0.2854, -0.1058,  0.0995],
        [-0.4452, -0.4190,  0.3878, -0.2256,  0.0755]], requires_grad=True)

In [23]:
model.linear1.bias

Parameter containing:
tensor([-0.4399,  0.2696, -0.0470], requires_grad=True)

In [24]:
model.linear2.weight

Parameter containing:
tensor([[-0.4831,  0.4663, -0.3507]], requires_grad=True)

In [25]:
model.linear2.bias

Parameter containing:
tensor([0.5724], requires_grad=True)

## Data --> shape(10,5)
- linear1(5,3) --> no.of weights = 5 and no. of biases = 3, total_no of parameters = 5x3 + 3 = 18
- linear2(3,1) --> no.of weights = 3 and no. of biases = 1, total_no of parameters = 3x1 + 1 = 4

In [26]:
# create model class
# Using Sequential function here, so, we don't have to write the whole parameters again in the forward method, we can call the variable where the sequential parameter is stored
import torch
import torch.nn as nn

class Model(nn.Module):

  def __init__(self, num_features):

    super().__init__()
    self.network = nn.Sequential(
        nn.Linear(num_features, 3),
        nn.ReLU(),
        nn.Linear(3, 1),
        nn.Sigmoid()
    )

  def forward(self, features):

    out = self.network(features)

    return out

In [27]:
data = torch.rand(10,5)

In [28]:
model1 = Model(data.shape[1]) # n_features = 5

In [29]:
model1(data)

tensor([[0.4150],
        [0.4310],
        [0.4404],
        [0.4080],
        [0.4017],
        [0.4496],
        [0.4490],
        [0.4326],
        [0.4523],
        [0.4310]], grad_fn=<SigmoidBackward0>)

In [30]:
!pip install torchinfo

In [31]:
# Summary
from torchinfo import summary

In [32]:
summary(model1,input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Sequential: 1-1                        [10, 1]                   --
│    └─Linear: 2-1                       [10, 3]                   18
│    └─ReLU: 2-2                         [10, 3]                   --
│    └─Linear: 2-3                       [10, 1]                   4
│    └─Sigmoid: 2-4                      [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

In [33]:
import pandas as pd
df = pd.read_csv("https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv")

In [34]:
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [35]:
df["diagnosis"].value_counts()

diagnosis
B    357
M    212
Name: count, dtype: int64

In [36]:
df.shape

(569, 33)

In [37]:
df.columns

Index(['id', 'diagnosis', 'radius_mean', 'texture_mean', 'perimeter_mean',
       'area_mean', 'smoothness_mean', 'compactness_mean', 'concavity_mean',
       'concave points_mean', 'symmetry_mean', 'fractal_dimension_mean',
       'radius_se', 'texture_se', 'perimeter_se', 'area_se', 'smoothness_se',
       'compactness_se', 'concavity_se', 'concave points_se', 'symmetry_se',
       'fractal_dimension_se', 'radius_worst', 'texture_worst',
       'perimeter_worst', 'area_worst', 'smoothness_worst',
       'compactness_worst', 'concavity_worst', 'concave points_worst',
       'symmetry_worst', 'fractal_dimension_worst', 'Unnamed: 32'],
      dtype='object')

In [42]:
df = df.drop(columns=["id","Unnamed: 32"])

In [43]:
df.head()

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0         M        17.99         10.38          122.80     1001.0   
1         M        20.57         17.77          132.90     1326.0   
2         M        19.69         21.25          130.00     1203.0   
3         M        11.42         20.38           77.58      386.1   
4         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0         0.2419  ...         25.38          17.33           184.60   
1         0.1812  ...         24.99          23.41           158.80   
2         0.2069  ...         23.57          25.53           152.50   
3         0.2597  ...         14.91          26.50            98.87   
4         0.1809  ...         22.54          16.67           152.20   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 31 columns]

In [44]:
df["diagnosis"].value_counts() # B -> Benign and M -> Maligant

diagnosis
B    357
M    212
Name: count, dtype: int64

In [45]:
X = df.drop(columns=["diagnosis"]) # df.iloc[:,1]
y = df["diagnosis"] # df.iloc[:,0]

In [47]:
X.head(2)

radius_mean  texture_mean  perimeter_mean  area_mean  smoothness_mean  \
0        17.99         10.38           122.8     1001.0          0.11840   
1        20.57         17.77           132.9     1326.0          0.08474   

   compactness_mean  concavity_mean  concave points_mean  symmetry_mean  \
0           0.27760          0.3001              0.14710         0.2419   
1           0.07864          0.0869              0.07017         0.1812   

   fractal_dimension_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0                 0.07871  ...         25.38          17.33            184.6   
1                 0.05667  ...         24.99          23.41            158.8   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  

[2 rows x 30 columns]

In [50]:
y.head(2)

0    M
1    M
Name: diagnosis, dtype: object

In [51]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import  train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [52]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [53]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [55]:
X_train

array([[-1.44075296, -0.43531947, -1.36208497, ...,  0.9320124 ,
         2.09724217,  1.88645014],
       [ 1.97409619,  1.73302577,  2.09167167, ...,  2.6989469 ,
         1.89116053,  2.49783848],
       [-1.39998202, -1.24962228, -1.34520926, ..., -0.97023893,
         0.59760192,  0.0578942 ],
       ...,
       [ 0.04880192, -0.55500086, -0.06512547, ..., -1.23903365,
        -0.70863864, -1.27145475],
       [-0.03896885,  0.10207345, -0.03137406, ...,  1.05001236,
         0.43432185,  1.21336207],
       [-0.54860557,  0.31327591, -0.60350155, ..., -0.61102866,
        -0.3345212 , -0.84628745]])

In [56]:
y_test

array([0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0,
       1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0,
       1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0,
       1, 0, 0, 1])

In [57]:
# Converting normal arrays into tensors
X_train_tensor = torch.from_numpy(X_train.astype(np.float32))
X_test_tensor = torch.from_numpy(X_test.astype(np.float32))
y_train_tensor = torch.from_numpy(y_train.astype(np.float32))
y_test_tensor = torch.from_numpy(y_test.astype(np.float32))


In [58]:
X_train_tensor

tensor([[-1.4408, -0.4353, -1.3621,  ...,  0.9320,  2.0972,  1.8865],
        [ 1.9741,  1.7330,  2.0917,  ...,  2.6989,  1.8912,  2.4978],
        [-1.4000, -1.2496, -1.3452,  ..., -0.9702,  0.5976,  0.0579],
        ...,
        [ 0.0488, -0.5550, -0.0651,  ..., -1.2390, -0.7086, -1.2715],
        [-0.0390,  0.1021, -0.0314,  ...,  1.0500,  0.4343,  1.2134],
        [-0.5486,  0.3133, -0.6035,  ..., -0.6110, -0.3345, -0.8463]])

In [59]:
type(X_train), type(X_train_tensor)

(numpy.ndarray, torch.Tensor)